name: $(Date:yyyyMMdd)-$(Build.BuildId)

trigger:
- main
- master

resources:
- repo: self

variables:
- group: common

extends:
  template: pipeline-template.yaml
  parameters:
      repository: "tasker-proxy"
      multi_arch: "false"