name: $(Date:yyyyMMdd)-$(Build.BuildId)

trigger:
- main
- master

resources:
- repo: self

variables:
- group: common
- name: multiarch
  ${{ if eq(PLATFORMS, 'linux/arm64') }}:
    value: false
  ${{ else }}:
    value: true

extends:
  template: pipeline-template.yaml
  parameters:
      repository: "tasker-proxy"
      multiarch: "${{variables.multiarch}}"